version depend on enable not working
In a FreeBSD 10.0-RELEASE jail with puppet 3.6.2_1 I would get the following error when using this module:

```tcsh
Could not retrieve fact='pkgng_version', resolution='<anonymous>': undefined method `pkgng_enabled' for Facter:Module
Could not retrieve fact='pkgng_version', resolution='<anonymous>': undefined method `pkgng_enabled' for Facter:Module
Could not retrieve fact='pkgng_version', resolution='<anonymous>': undefined method `pkgng_enabled' for Facter:Module
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: PKGng is either not supported on your system or it is too old at /usr/local/etc/puppet/modules/pkgng/manifests/init.pp:18
```

Using the same check as is used to determine pkgng_enabled works fine for me.